pipeline:
  clone:
    image: plugins/git
    tags: true

  build:
    image: golang:1.11
    secrets: [github_token]
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag
