---
kind: pipeline
name: default
type: kubernetes

steps:
  - name: clone tags
    image: plugins/git
    settings:
      tags: true

  - name: build
    image: golang:1.11
    commands:
      - "curl -sL https://git.io/goreleaser | bash"
    environment:
      GITHUB_TOKEN:
        from_secret: github_token

trigger:
  event:
    - tag
